name: 'Setup java and gradle'
description: 'My setup'

runs:
  using: "composite"
  steps:
    # A small utility action that takes a file with key=value pairs and sets them as environment variables for the rest of the workflow.
    - name: Set Environment Variables
      uses: ./.github/actions/set-vars
      with:
        filePath: ./.github/variables/java_config.env

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Cache Gradle dependencies
      uses: gradle/actions/setup-gradle@v5

    - name: Configure Gradle
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cat <<EOF >> ~/.gradle/gradle.properties
        org.gradle.caching=true
        org.gradle.configuration-cache=true
        org.gradle.parallel=true
        EOF
