---
name: PR verification

# What triggers this workflow
on:
  pull_request: # Pull requests
  push: # Merges to master
    branches:
      - 'master'
  workflow_dispatch: # Manual trigger

# Concurrency defines how many concurrent runs of this workflow are allowed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verification:
    name: PR Verification
    runs-on: ubuntu-latest # Machine this workflow will run on. Other Github-hosted runners include: windows-latest, macos-latest.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch full commit history. Usually needed for SonarQube analysis.
          ref: ${{ github.event.pull_request.head.sha }} # Actual PR commit (HEAD).

      - name: Setup java
        uses: ./.github/actions/my-config

      - name: Build project
        run: ./gradlew assemble

      - name: Run unit tests
        run: ./gradlew test --rerun coverage

      # Here we upload the test reports as artifacts. They are needed for the SonarQube analysis in the next step, but not in this case as scanning is faked here.
      - name: Archive reports
        uses: actions/upload-artifact@v7
        with:
          name: unit_test_reports
          path: |
            **/build/**/jacoco*.xml
            **/build/classes/

      # Fake SonarQube scan.
      - name: Run Sonar Scan
        run: |
          SONAR_SCAN_SCRIPT='./.github/scripts/sonar_scan.sh'
          chmod +x "${SONAR_SCAN_SCRIPT}"
          "${SONAR_SCAN_SCRIPT}"

  lint:
    name: PR Verification
    runs-on: ubuntu-latest # Machine this workflow will run on. Other Github-hosted runners include: windows-latest, macos-latest.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch full commit history. Usually needed for SonarQube analysis.
          ref: ${{ github.event.pull_request.head.sha }} # Actual PR commit (HEAD).

      - name: Setup java
        uses: ./.github/actions/my-config

      - name: Run spotless check
        run: ./gradlew spotlessCheck
