---
name: PR verification

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verification:
    name: PR Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup JDK and Gradle
        uses: ./.github/actions/my-setup

      - name: Run spotless check
        run: ./gradlew spotlessCheck

      - name: Build project
        run: ./gradlew assemble

      - name: Run unit tests
        run: ./gradlew test --rerun coverage

      - name: Archive reports
        uses: actions/upload-artifact@v7
        with:
          name: unit_test_reports
          path: |
            **/build/**/jacoco*.xml
            **/build/classes/

      - name: Run Sonar Scan
        run: |
          SONAR_SCAN_SCRIPT='./.github/scripts/sonar_scan.sh'
          chmod +x "${SONAR_SCAN_SCRIPT}"
          "${SONAR_SCAN_SCRIPT}"
